sudo: false

language: rust

rust:
  # For now, disable stable, until Rust 2018 becomes stable.
  #    - stable
    - beta
    - nightly

matrix:
    allow_failures:
        - rust: nightly

script:
    - cargo build
    - cargo test
