language: rust

before_install:
  - sudo apt-get install -y cssc

rust:
    - stable
    - beta
    - nightly

matrix:
    allow_failures:
        - rust: nightly

script:
    - cargo build
    - cargo test
    - cd weave
    - cargo build
    - cargo test
