[package]
name = "rsure"
version = "0.2.0"
authors = ["David Brown <davidb@davidb.org>"]

[dependencies]
libc = "*"
clap = "*"
flate2 = "*"
log = "*"
openssl = "*"
rustc-serialize = "*"

# This will go away
env_logger = "*"
