[package]
name = "rsure"
version = "0.3.5"
authors = ["David Brown <davidb@davidb.org>"]
description = "File integrity"
license = "MIT"

[dependencies]
libc = "0.2.11"
clap = "2.5.2"
flate2 = "0.2"
log = "0.3"
openssl = "0.7"
rustc-serialize = "0.3"
regex = "0.1"
time = "0.1"
error-chain = "0.1.12"

# This will go away
env_logger = "0.3"

[dev-dependencies]
tempdir = "0.3.4"

[[bin]]
name = "rsure"
test = false
doc = false
