[package]
name = "rsure"
version = "0.6.0"
authors = ["David Brown <davidb@davidb.org>"]
description = """
Rsure captures hashes and metadata about a tree of files, and can
later verify these hashes and metadata to determine if the files have
changed.  It supports incremental updates, and includes an standalone
executable for scanning and checking trees.
"""
license = "MIT"
readme = "README.rst"
repository = "https://github.com/d3zd3z/rsure"

exclude = [
    "2sure.*.gz"
]

[dependencies]
libc = "0.2.11"
clap = "2.5.2"
flate2 = "0.2"
log = "0.3"
openssl = "0.7"
rustc-serialize = "0.3"
regex = "0.1"
time = "0.1"
error-chain = "0.2"

# This will go away
env_logger = "0.3"

[dev-dependencies]
tempdir = "0.3.4"

[[bin]]
name = "rsure"
test = false
doc = false
