[package]
name = "rsure"
version = "0.3.0"
authors = ["David Brown <davidb@davidb.org>"]
description = "File integrity"
license = "MIT"

[dependencies]
libc = "*"
clap = "*"
flate2 = "*"
log = "*"
openssl = "*"
rustc-serialize = "*"
regex = "*"
time = "*"

# This will go away
env_logger = "*"

[[bin]]
name = "rsure"
test = false
doc = false
