[package]
name = "weave"
version = "0.1.0"
authors = ["davidb"]

[dependencies]
error-chain = "0.10"
derive-error-chain = "0.10"

[dev-dependencies]
env_logger = "0.4"
log = "0.3"
rand = "0.3"
tempdir = "0.3"
